const data = {
	"A": {"value":1,  "amount":9},
	"B": {"value":3,  "amount":2},
	"C": {"value":3,  "amount":2},
	"D": {"value":2,  "amount":4},
	"E": {"value":1,  "amount":12},
	"F": {"value":4,  "amount":2},
	"G": {"value":2,  "amount":3},
	"H": {"value":4,  "amount":2},
	"I": {"value":1,  "amount":9},
	"J": {"value":8,  "amount":1},
	"K": {"value":5,  "amount":1},
	"L": {"value":1,  "amount":4},
	"M": {"value":3,  "amount":2},
	"N": {"value":1,  "amount":6},
	"O": {"value":1,  "amount":8},
	"P": {"value":3,  "amount":2},
	"Q": {"value":10, "amount":1},
	"R": {"value":1,  "amount":6},
	"S": {"value":1,  "amount":4},
	"T": {"value":1,  "amount":6},
	"U": {"value":1,  "amount":4},
	"V": {"value":4,  "amount":2},
	"W": {"value":4,  "amount":2},
	"X": {"value":8,  "amount":1},
	"Y": {"value":4,  "amount":2},
	"Z": {"value":10, "amount":1},
	"_": {"value":0,  "amount":2}
};

